name: Release Update

on:
  push:
    branches:
      - master

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}